liquidinvestigations/hoover-search

CHANGES.md
hoover/search/es.py
hoover/site/settings/common.py
hoover/site/settings/example_local.py
hoover/site/settings/example_testing_local.py
testsuite/settings.py
testsuite/test_search.py

Rename the ELASTICSEARCH_URL to HOOVER_ELASTICSEARCH_URL for consistency with snoop.

Fix initial setup

---

hoover/search/middleware.py
hoover/search/views.py
hoover/site/urls.py

Cache all documents from UI for 1 year, except for html files.

UI caching

---

Readme.md
hoover/search/loaders/collectible.py
hoover/search/loaders/external.py
hoover/search/loaders/upload.py
hoover/search/loaders/webdav.py
hoover/search/ui.py
hoover/search/views.py
hoover/site/urls.py

~~Please don't merge this yet. It depends on hoover-ui providing a functional `doc.html`.~~
Ok, I think this patch is ready, and should not break existing collections.

For the document preview page, serve doc.html from ui

---

hoover/search/es.py
hoover/search/views.py

Don't merge this without https://github.com/hoover/ui/pull/8.

Report errors to the UI when Elasticsearch either fails to respond or responds with an error

---

requirements.in
requirements.txt

All tests pass.
Same as [https://github.com/hoover/snoop/pull/27](https://github.com/hoover/snoop/pull/27).

update dependency versions

---

hoover/search/loaders/external.py
hoover/search/ui.py

Depends on [this commit](https://github.com/hoover/ui/pull/9/commits/32c984a1) in `hoover-ui`.

embed the document's json in the html

---

hoover/search/management/commands/doctor.py

@mgax Please suggest more checks.
Which of the following checks might be of worth:
- collections
- `external` collections have working endpoints
- collections have working elasticsearch indexes / aliases
- contrib modules 
- twofactor / oauth2 endpoints work (which endpoints?)
- ratelimit time constants are OK / nonzero? / nonnegative?
Anything else to be checked? Maybe some other directories that should be writeable? Are there any system executables being used, like `pdftotext`?

first implementation of the all-checking doctor

---

hoover/search/es.py
hoover/search/views.py

This is necessary to properly implement the facet filters
requested in hoover/ui#24.

Accept post_filter param for /search endpoint.

---

hoover/search/es.py
hoover/search/views.py
requirements.txt
testsuite/test_search.py

Updates for ES6.

---

.travis.yml
Dockerfile
testsuite/docker-compose.override.travis.yml
testsuite/test_search.py

Also skipped one failing tests as per @mgax's comment.

Add test setup using Docker (similar to the hoover/snoop2 tests)

---

Dockerfile
hoover/site/settings/docker_local.py

Improve the docker configuration so that it can pull values directly fom the environment without the need to mount a config file.

Liquid nomad

---

hoover/contrib/oauth2/views.py
hoover/site/settings/docker_local.py
requirements.in
requirements.txt

Allow configuration of OAuth2 keys and URLs via environment variables.

Liquid oauth2

---

hoover/contrib/oauth2/views.py

Depends on https://github.com/liquidinvestigations/core/pull/46

Follow the `is_admin` flag from oauth server

---

hoover/search/management/commands/setcollectiontitle.py

Needed for https://github.com/CRJI/EIC/issues/198

add set collection title command

---

hoover/search/admin.py

fixes https://github.com/liquidinvestigations/node/issues/97

Fix many to many related field name

---

hoover/site/settings/common.py
hoover/site/settings/docker_local.py
testsuite/settings.py

https://github.com/CRJI/EIC/issues/252

enable ratelimit when 2fa was disabled, make it configurable

---

testsuite/docker-compose.travis.yml

Let's see if it all still works
For https://github.com/liquidinvestigations/node/pull/201

test with elasticsearch 6.8.3

---

Readme.md

I just fixed a minor mistake in the README.  😃 
* `README.md`

Fixing typo in README.md

---

hoover/search/management/commands/createstatsindex.py

Snoop stats

---

hoover/search/admin.py
hoover/search/views.py
hoover/site/urls.py

closes https://github.com/CRJI/EIC/issues/305
closes https://github.com/CRJI/EIC/issues/649
closes https://github.com/CRJI/EIC/issues/657

fix pdf redirects and admin edit rights

---

hoover/search/views.py

closes https://github.com/CRJI/EIC/issues/630

enforce field list coming from front-end

---

hoover/search/loaders/external.py
hoover/site/settings/common.py

forward range headers to snoop

---

hoover/search/management/commands/getuuid.py

getuuid command

---

hoover/search/tasks.py

Nextcloud groupfolders
